"""Immutable report/API compatibility metadata owned by the VNext runtime."""

import hashlib


# Keep this value in lockstep with docs/api_contract.json. It identifies the
# DTO/route contract a generated report expects; it is not a release number.
REPORT_API_CONTRACT_VERSION = "vnext-api-20260822.1"
REPORT_COMPATIBILITY_VERSION = 1
_RELEASE_FIELDS = (
    "version", "commit_sha", "build_id", "asset_hash", "schema_version",
)


def stable_release_identity(release_identity):
    """Return only immutable release fields suitable for report metadata."""
    if not release_identity:
        return {}
    if not isinstance(release_identity, dict):
        raise ValueError("release identity must be an object")
    missing = [
        key for key in _RELEASE_FIELDS
        if release_identity.get(key) in (None, "")
    ]
    if missing:
        raise ValueError("release identity is incomplete: " + ", ".join(missing))
    return {key: release_identity[key] for key in _RELEASE_FIELDS}


def derive_asset_identity(release_identity, api_contract_version=None):
    """Build a bounded identity token for ``coverage_reports.asset_identity``."""
    release = stable_release_identity(release_identity)
    api_version = str(api_contract_version or REPORT_API_CONTRACT_VERSION)
    contract_digest = hashlib.sha256(api_version.encode("utf-8")).hexdigest()[:12]
    return "v{}:{}:{}:{}".format(
        REPORT_COMPATIBILITY_VERSION,
        str(release["commit_sha"]),
        str(release["asset_hash"]),
        contract_digest,
    )


def with_report_compatibility(report, release_identity=None,
                              api_contract_version=None):
    """Attach immutable compatibility metadata to a newly generated report.

    Historical callers may provide an explicit ``asset_identity``. It is
    preserved for compatibility, while reports generated by the canonical
    runtime receive exact release/API metadata automatically.
    """
    if not report:
        return report
    payload = dict(report)
    if not release_identity:
        return payload
    api_version = str(api_contract_version or REPORT_API_CONTRACT_VERSION)
    expected_release = stable_release_identity(release_identity)
    declared_api = payload.get("api_contract_version")
    if declared_api not in (None, "", api_version):
        raise ValueError("REPORT_API_CONTRACT_MISMATCH")
    declared_release = payload.get("release_identity")
    if declared_release:
        if stable_release_identity(declared_release) != expected_release:
            raise ValueError("REPORT_RELEASE_IDENTITY_MISMATCH")
    payload["api_contract_version"] = api_version
    payload["release_identity"] = expected_release
    if not payload.get("asset_identity"):
        payload["asset_identity"] = derive_asset_identity(
            expected_release, api_contract_version=api_version
        )
    return payload
